### ISSUE TITLE
.gitconfigのtypo

### ISSUE THREAD

**Issue by kk-itaoyagi** [yagi2/dotfiles#5]

**Comment by kk-itaoyagi** [comment]
`fr = "!$SHELL -c 'git diff --name-only | peco -prompt \"File>\" | xargs git checkout' __dummy__" # file reset`
pecoのオプションにハイフン1つ足りない

**Comment by yagi2** [comment]
https://github.com/yagi2/dotfiles/commit/9ff3004e37c0d0a8dab79d51519071bdc805cd5f DONE
